tor-ft-docker1.points.com:
  roles:
    docker_host:
      node: list-loading-service-ft-1.lxc.points.com
      enable_nscd: True
      dependencies: ['http://tor-ft-es1.points.com:9200', 'http://tor-ft-es2.points.com:9200', 'http://tor-ft-es3.points.com:9200']
    lb_config_node:
      load_balancer_host: list-loading-service-ft.lxc.points.com
      load_balancer_port: 2000
      node_port: 8080
      nodes: [list-loading-service-ft-1.lxc.points.com, list-loading-service-ft-2.lxc.points.com]
      mode: roundrobin
    seed_sanity_test_file:
      node: list-loading-service-ft-1.lxc.points.com

tor-ft-docker2.points.com:
  roles:
    docker_host:
      node: list-loading-service-ft-2.lxc.points.com
      enable_nscd: True
      dependencies: ['http://tor-ft-es1.points.com:9200', 'http://tor-ft-es2.points.com:9200', 'http://tor-ft-es3.points.com:9200']