tp-list-loading-service1.points.com:
  roles:
    docker_host:
      node: list-loading-service1.prd.points.com
      enable_nscd: True
      dependencies: []
    lb_config_node:
      load_balancer_host: list-loading-service.prd.points.com
      load_balancer_port: 2000
      node_port: 8080
      nodes: [list-loading-service1.prd.points.com, list-loading-service2.prd.points.com]
    elastic_search_lb_config_node:
      load_balancer_host: list-loading-service.prd.points.com
      load_balancer_port: 9200
      node_port: 9200
      nodes: [tp-es1.points.com, tp-es2.points.com, tp-es3.points.com]
      mode: roundrobin
    seed_sanity_test_file:
      node: list-loading-service1.prd.points.com

tp-list-loading-service2.points.com:
  roles:
    docker_host:
      node: list-loading-service2.prd.points.com
      enable_nscd: True
      dependencies: []