tor-st-docker1.points.com:
  roles:
    docker_host:
      node: list-loading-service-st-1.lxc.points.com
      enable_nscd: True
      dependencies: []
    lb_config_node:
      load_balancer_host: list-loading-service-st.lxc.points.com
      load_balancer_port: 2000
      node_port: 8080
      nodes: [list-loading-service-st-1.lxc.points.com, list-loading-service-st-2.lxc.points.com]

tor-st-docker2.points.com:
  roles:
    docker_host:
      node: list-loading-service-st-2.lxc.points.com
      enable_nscd: True
      dependencies: []